#!/usr/bin/env node

const path = process.cwd()
const args = process.argv

const fs = require('fs')
const yaml = require('js-yaml')
const colors = require('colors')
const debug = require('./source/utils/debug')
const { version } = require('./package.json')

// check config file
fs.exists(`${path}/isopack.yml`, exists => {
  if (exists) {

    // load isopack.yml
    const config = yaml.safeLoad(
      fs.readFileSync(`${path}/isopack.yml`, 'utf8')
    )

    // require and start isopack
    require('./source/index.js')({
      version,
      config,
      args,
      path 
    });

  } else process.stderr.write(
    colors.red(`ISOPACK: can't find isopack.config.js here '${path}'`)
  )
})
